function [xld_H, xld_V] = calculate_xld(mx, my, mz, R, pol_H, pol_V)
    [cfg, vec] = astra_initialize(size(mx),R);
    split = 1;
    proj_xx=astra.Ax_partial(mx.*mx, cfg, vec, split);
    proj_xy=astra.Ax_partial(mx.*my, cfg, vec, split);
    proj_xz=astra.Ax_partial(mx.*mz, cfg, vec, split);
    proj_yy=astra.Ax_partial(my.*my, cfg, vec, split);
    proj_yz=astra.Ax_partial(my.*mz, cfg, vec, split);
    proj_zz=astra.Ax_partial(mz.*mz, cfg, vec, split);
    
    xld_H=zeros(size(proj_xx,1),size(proj_xx,2),size(proj_xx,3));
    xld_V=zeros(size(xld_H));
    for ii = 1:size(R,3)
        RR = R(:,:,ii);
        xld_H(:,:,ii) = proj_xx(:,:,ii)  *(RR(1,1)*cosd(pol_H)+RR(2,1)*sind(pol_H))^2 + ...
                        proj_yy(:,:,ii)  *(RR(1,2)*cosd(pol_H)+RR(2,2)*sind(pol_H))^2 + ...
                        proj_zz(:,:,ii)  *(RR(1,3)*cosd(pol_H)+RR(2,3)*sind(pol_H))^2 + ...
                        2*proj_xy(:,:,ii)*(RR(1,1)*cosd(pol_H)+RR(2,1)*sind(pol_H))*(RR(1,2)*cosd(pol_H)+RR(2,2)*sind(pol_H)) + ...
                        2*proj_xz(:,:,ii)*(RR(1,1)*cosd(pol_H)+RR(2,1)*sind(pol_H))*(RR(1,3)*cosd(pol_H)+RR(2,3)*sind(pol_H)) + ...
                        2*proj_yz(:,:,ii)*(RR(1,2)*cosd(pol_H)+RR(2,2)*sind(pol_H))*(RR(1,3)*cosd(pol_H)+RR(2,3)*sind(pol_H));
        xld_V(:,:,ii) = (proj_xx(:,:,ii)  *(RR(1,1)*cosd(pol_V)+RR(2,1)*sind(pol_V))^2 + ...
                        proj_yy(:,:,ii)  *(RR(1,2)*cosd(pol_V)+RR(2,2)*sind(pol_V))^2 + ...
                        proj_zz(:,:,ii)  *(RR(1,3)*cosd(pol_V)+RR(2,3)*sind(pol_V))^2 + ...
                        2*proj_xy(:,:,ii)*(RR(1,1)*cosd(pol_V)+RR(2,1)*sind(pol_V))*(RR(1,2)*cosd(pol_V)+RR(2,2)*sind(pol_V)) + ...
                        2*proj_xz(:,:,ii)*(RR(1,1)*cosd(pol_V)+RR(2,1)*sind(pol_V))*(RR(1,3)*cosd(pol_V)+RR(2,3)*sind(pol_V)) + ...
                        2*proj_yz(:,:,ii)*(RR(1,2)*cosd(pol_V)+RR(2,2)*sind(pol_V))*(RR(1,3)*cosd(pol_V)+RR(2,3)*sind(pol_V)));
    end
end